FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish Jellyfin.Server/Jellyfin.Server.csproj \
    --configuration Release \
    --runtime linux-x64 \
    --self-contained true \
    --output /out \
    -p:DebugType=none \
    -p:DebugSymbols=false \
    -p:PublishSingleFile=false

FROM jellyfin/jellyfin:latest
COPY --from=build /out/ /jellyfin/
